[build]
  base = "."
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SCHEDULER_API_URL = "https://scheduler3-723515091945.europe-north2.run.app"
  VITE_ENABLE_SCHEDULER_API = "true"
  VITE_ENABLE_LOCAL_FALLBACK = "true"
  VITE_ENABLE_DEV_TOOLS = "false"
