
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Dialog, DialogContent, DialogTrigger, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { UserPlus } from "lucide-react";
import { AddProfileDialog } from "@/components/directory/AddProfileDialog";
import { useDirectory } from "@/contexts/DirectoryContext";
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { InsertProfile } from "@/types/profile";
import { addProfile } from "@/services/profileService";

export function DirectoryControls() {
  const { roleFilter, setRoleFilter, searchQuery, setSearchQuery } = useDirectory();
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [newProfile, setNewProfile] = useState<InsertProfile>({
    id: '',
    first_name: '',
    last_name: '',
    role: '',
    department: '',
    phone: '',
    experience_level: 1
  });
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsProcessing(true);
    
    try {
      console.log("Adding new profile with data:", newProfile);
      
      // Create profile data object without the ID (will be generated by the function)
      const profileData = {
        first_name: newProfile.first_name,
        last_name: newProfile.last_name,
        role: newProfile.role,
        department: newProfile.department || '',
        phone: newProfile.phone || '',
        experience_level: Number(newProfile.experience_level)
      };
      
      // Use the profile service to add the profile
      const addedProfile = await addProfile(profileData);
      
      console.log("Profile added successfully:", addedProfile);
      
      toast({
        title: "Profil tillagd",
        description: `${profileData.first_name} ${profileData.last_name} har lagts till`,
      });
      
      // Reset form
      setNewProfile({
        id: '',
        first_name: '',
        last_name: '',
        role: '',
        department: '',
        phone: '',
        experience_level: 1
      });
      
      // Refresh the profiles list
      await queryClient.invalidateQueries({ queryKey: ['profiles'] });
      setIsDialogOpen(false);
    } catch (error: any) {
      console.error('Error adding profile:', error);
      
      let errorMessage = "Kunde inte lägga till profilen";
      
      // Handle specific errors related to experience_level
      if (error.message && (
        error.message.includes("experience_level") || 
        error.message.includes("profiles_experience_level_check")
      )) {
        errorMessage = "Erfarenhetsnivå måste vara mellan 0 och 10 år";
      } else if (error.message && error.message.includes("constraint")) {
        errorMessage = "Ett fel uppstod med databasen. Kontrollera att alla fält är korrekt ifyllda.";
      } else if (error.message) {
        errorMessage = error.message;
      }
      
      toast({
        title: "Fel",
        description: errorMessage,
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-slate-200/50">
      <div className="flex flex-col lg:flex-row gap-4 items-start lg:items-center justify-between">
        {/* Search and Filter Section */}
        <div className="flex flex-col sm:flex-row gap-3 w-full lg:w-auto">
          <div className="relative">
            <Input
              placeholder="Sök personal..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full sm:w-[320px] h-11 pl-4 pr-4 border-slate-300 rounded-lg shadow-sm focus:border-blue-500 focus:ring-blue-500/20 transition-all duration-200"
            />
          </div>
          <Select
            value={roleFilter}
            onValueChange={setRoleFilter}
          >
            <SelectTrigger className="w-full sm:w-[200px] h-11 border-slate-300 rounded-lg shadow-sm focus:border-blue-500 focus:ring-blue-500/20 transition-all duration-200">
              <SelectValue placeholder="Alla roller" />
            </SelectTrigger>
            <SelectContent className="rounded-lg border-slate-300 shadow-lg">
              <SelectItem value="all" className="rounded-md">Alla roller</SelectItem>
              <SelectItem value="Läkare" className="rounded-md">Läkare</SelectItem>
              <SelectItem value="Sjuksköterska" className="rounded-md">Sjuksköterska</SelectItem>
              <SelectItem value="Undersköterska" className="rounded-md">Undersköterska</SelectItem>
            </SelectContent>
          </Select>
        </div>
        
        {/* Add Employee Button */}
        <div className="w-full lg:w-auto">
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
              <Button className="w-full lg:w-auto h-11 px-6 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-medium rounded-lg shadow-sm transition-all duration-200 hover:shadow-md">
                <UserPlus className="w-4 h-4 mr-2" />
                Lägg till personal
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-2xl">
              <DialogTitle className="text-xl font-semibold text-gray-900 dark:text-gray-100 flex items-center gap-3">
                <div className="w-8 h-8 bg-green-100 dark:bg-green-900/30 rounded-lg flex items-center justify-center">
                  <UserPlus className="w-4 h-4 text-green-600 dark:text-green-400" />
                </div>
                Lägg till ny medarbetare
              </DialogTitle>
              <DialogDescription className="text-gray-600 dark:text-gray-400">
                Fyll i informationen nedan för att lägga till en ny medarbetare i systemet.
              </DialogDescription>
              <AddProfileDialog 
                isOpen={isDialogOpen}
                setIsOpen={setIsDialogOpen}
                newProfile={newProfile}
                setNewProfile={setNewProfile}
                onSubmit={handleSubmit}
                isProcessing={isProcessing}
              />
            </DialogContent>
          </Dialog>
        </div>
      </div>
    </div>
  );
}
